global using System.Diagnostics.CodeAnalysis;
global using System.Text;
global using Poker.Domain.Abstractions;
global using Poker.Domain.Classic;
global using Poker.Domain.Delegates;
global using Poker.Domain.Extensions;
global using Poker.Domain.Messaging;
global using Poker.Domain.Messaging.Extensions;
global using Poker.Utility;
